name: flutter_contact
version: 0.9.1+7
homepage: https://github.com/SunnyApp/flutter_contact
description: A Flutter plugin to retrieve, create and save contacts and contact-related events on Android and iOS devices.
maintainer: Eric Martineau
environment: 
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=1.10.0'
dependencies: 
  collection: ^1.17.2
  equatable: ^2.0.5
  intl: ^0.18.1
  logging: 1.2.0
  quiver: ^3.0.1+1
  uuid: ^3.0.7
  dartxx: 
    git:
      url: https://github.com/kodyfanz/dartxx
      ref: master # commit hash/ branch
  flexidate: ^0.8.0+3
  logging_config: 
    git:
      url: https://github.com/kodyfanz/logging_config
      ref: master # commit hash/ branch
  flutter: 
    sdk: flutter
dev_dependencies: 
  pedantic: ^1.11.1
  flutter_test: 
    sdk: flutter
flutter: 
  plugin: 
    platforms: 
      android: 
        package: co.sunnyapp.flutter_contact
        pluginClass: FlutterContactPlugin
      ios: 
        pluginClass: FlutterContactPlugin
